name: Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch name to build'
        required: true
        default: 'kvm-nyx-5.10.73'

jobs:
  debian_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          path: sources

      - name: Install ccache
        run: sudo apt-get install -y ccache

      - name: Install build deps
        run: sudo apt-get install -y libelf-dev

      - name: Generate olddef config
        run: make x86_64_defconfig
        working-directory: sources
      
      - name: Configure kernel and enable Nyx
        run: |
          ./scripts/config --disable SYSTEM_TRUSTED_KEYS
          ./scripts/config --module CONFIG_KVM
          ./scripts/config --enable CONFIG_KVM_NYX
        working-directory: sources
        
      - name: Append Nyx to kernel version
        run: ./scripts/config --set-str CONFIG_LOCALVERSION -nyx
        working-directory: sources

      - uses: actions/cache@v3
        with:
          path: ~/.cache/ccache
          key: "${{ runner.os }}-${{ inputs.branch }}-${{ hashFiles('.config') }}"
          restore-keys: |
            "${{ runner.os }}-${{ inputs.branch }}"
            "${{ runner.os }}"

      - name: Build kernel
        run: |
          export PATH="/usr/lib/ccache:$PATH"
          make -j$(nproc) bindeb-pkg
        working-directory: sources

      - uses: actions/upload-artifact@v3
        with:
          name: linux-${{ inputs.branch }}
          path: '*.deb'
